




import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastián
 */
public class VentanaInicio extends javax.swing.JFrame {
    private boolean loginOk=false;
    Textos textos = new Textos();
    Imagenes imagenes = new Imagenes();
    java.net.URL rutaIcono = VentanaInicio.class.getResource("iconos/png/icono_zeppellin_16.png");
    
    ImageIcon icono = new ImageIcon(rutaIcono, "");
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btVerDir = new javax.swing.JButton();
        btSubirArch = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(textos.Nombre()+" "+textos.Version());
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        texto1.setColumns(20);
        texto1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        texto1.setRows(5);
        jScrollPane1.setViewportView(texto1);

        jButton1.setText("Ver Archivos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btVerDir.setText("Ver Directorio");
        btVerDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVerDirMouseClicked(evt);
            }
        });

        btSubirArch.setText("Subir Archivo");
        btSubirArch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSubirArchMouseClicked(evt);
            }
        });

        jButton2.setText("jButton2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cuenta:");

        btLogin.setText("Iniciar Sesión");
        btLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btVerDir)
                                .addGap(18, 18, 18)
                                .addComponent(btSubirArch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btVerDir)
                    .addComponent(btSubirArch)
                    .addComponent(jButton2))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        InfoDrive d1 = new InfoDrive();
        String r= "";
        try{
            r = d1.ListaDirectoriosDrive(null);
        }
        catch(IOException e){
            r= e.getMessage();
        }
        catch(GeneralSecurityException e){
            r=e.getMessage();
        }
        texto1.setText(r);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btVerDirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVerDirMouseClicked
        
        Archivos arch = new Archivos();
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        selector.setAcceptAllFileFilterUsed(false);
        int returnVal = selector.showOpenDialog(btVerDir);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File directorio=selector.getSelectedFile();
            arch.VerArchivos(directorio, texto1);
        }
    }//GEN-LAST:event_btVerDirMouseClicked

    private void btSubirArchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSubirArchMouseClicked
        Archivos arch = new Archivos();
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.FILES_ONLY);
        selector.setAcceptAllFileFilterUsed(false);
        int returnVal = selector.showOpenDialog(btSubirArch);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File directorio=selector.getSelectedFile();
            arch.SubirArchivo(directorio,texto1);
        }
    }//GEN-LAST:event_btSubirArchMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        texto1.setText("Iniciando el sistema...\n");
        Archivos a = new Archivos();
        a.ChequearDirCredenciales(texto1);
        texto1.append("Sistema Listo\n");
        
        Fecha fecha = new Fecha();
        //texto1.setText(fecha.Hoy());
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLoginMouseClicked
        InfoDrive info = new InfoDrive();
        
        if(!loginOk){
            try {
                String cuenta=info.NombreCuenta();
                String capacidad = info.CapacidadCuenta();
                btLogin.setText(cuenta);
                loginOk=true;
                texto1.append("\nConectado a "+cuenta);
                texto1.append("\nAlmacenamiento: "+capacidad+"\n");
            } catch (IOException ex) {
                texto1.append(ex.getMessage());
                //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            } catch (GeneralSecurityException ex) {
                texto1.append(ex.getMessage());
                //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            boolean salirOk=false;
            Alerta alerta = new Alerta(this, true);
            alerta.mensaje="¿Cerrar Sesión?";
            alerta.setVisible(true);
            //salirOk=alerta.getReturnStatus();
            
            if(alerta.getReturnStatus()==1){
               Archivos arch = new Archivos();
                arch.ChequearDirCredenciales(texto1);
                btLogin.setText("Iniciar Sesión");
                loginOk=false; 
            }
            
        }

        
        
    }//GEN-LAST:event_btLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btSubirArch;
    private javax.swing.JButton btVerDir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto1;
    // End of variables declaration//GEN-END:variables
}
